[임현지] Refactor: Feeds & Right 컴포넌트 분리 및 scss파일 정리
wecode-bootcamp-korea/10-React-Westagram-4 pull request #5
Opened 2020-07-09 07:30 UTC by imhyeonji

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
- 초기세팅 폴더 생성 & scss 정리
		 
## 수정 사항들 자세한 내용
- 각 팀원 이름 폴더 안에 Nav, Feeds, Right 등의 폴더 생성
- css를 scss 파일로 변경하면서 nesting 작업 진행

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2020-07-09 16:07 UTC, jamessoun93 requested changes

2020-07-09 16:07 UTC, jamessoun93 commented on src/Pages/hyeonji/Login/Login.js
> +  };
구분을 위해 아래 한줄을 비워주세요 :)

2020-07-09 16:07 UTC, jamessoun93 commented on src/Pages/hyeonji/Main/Feeds/Feeds.scss
> +  }
`.story` 를 기준으로 nesting이 가능하겠네요! 수정해주세요!

2020-07-09 16:07 UTC, jamessoun93 commented on src/Pages/hyeonji/Main/Feeds/Feeds.scss
> +  }
마찬가지입니다~

2020-07-09 16:07 UTC, jamessoun93 commented on src/Pages/hyeonji/Main/Feeds/Feeds.scss
> +  }
여기도 마찬가지입니다!

2020-07-10 02:58 UTC, imhyeonji commented on src/Pages/hyeonji/Login/Login.js
> +  };
수정완료했습니다 :)

2020-07-10 02:58 UTC, imhyeonji commented on src/Pages/hyeonji/Main/Feeds/Feeds.scss
> +  }
수정완료했습니다 :)

2020-07-10 02:58 UTC, imhyeonji commented on src/Pages/hyeonji/Main/Feeds/Feeds.scss
> +  }
수정완료했습니다 :)

2020-07-10 02:59 UTC, imhyeonji commented on src/Pages/hyeonji/Main/Feeds/Feeds.scss
> +  }
수정완료했습니다 :) 항상 감사드려요!

2020-07-10 05:27 UTC, jamessoun93 commented
크 라벨 사용법 말씀도 안드렸는데 알아서 해주시다니 🙇🏻‍♂️🙇🏻‍♂️🙇🏻‍♂️

LGTM! 고생하셨습니다 👍

2020-07-10 05:27 UTC, merged